import 'dart:html' as html;
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../quiz/quiz_session.dart';
import '../results/recommendation_result.dart';
import '../roadmap/roadmap_plan.dart';
import 'pdf_generator.dart';

class PdfExportSheet extends StatefulWidget {
  final CareerRecommendation match;
  final RoadmapPlan roadmap;
  final QuizSession session;

  const PdfExportSheet({
    super.key,
    required this.match,
    required this.roadmap,
    required this.session,
  });

  @override
  State<PdfExportSheet> createState() => _PdfExportSheetState();
}

class _PdfExportSheetState extends State<PdfExportSheet> {
  bool _generating = true;
  bool _done = false;
  String? _error;
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    _generatePdf();
  }

  Future<void> _generatePdf() async {
    try {
      setState(() => _error = null);

      final doc = await PdfExportGenerator.generate(
        match: widget.match,
        roadmap: widget.roadmap,
        session: widget.session,
      );

      final bytes = await doc.save();
      final pdfBytes = Uint8List.fromList(bytes);

      if (!mounted) return;
      setState(() {
        _pdfBytes = pdfBytes;
        _generating = false;
        _done = true;
      });
    } catch (e) {
      if (!mounted) return;
      final errorMsg = e.toString();
      final shortMsg = errorMsg.length > 120
          ? '${errorMsg.substring(0, 120)}...'
          : errorMsg;
      setState(() {
        _generating = false;
        _error =
            'Failed to generate PDF.\n\nError: $shortMsg\n\nPlease try again or check your data.';
      });
    }
  }

  Future<void> _downloadPdf() async {
    if (_pdfBytes == null) return;
    final blob = html.Blob([_pdfBytes], 'application/pdf');
    final url = html.Url.createObjectUrlFromBlob(blob);
    // ignore: unused_local_variable
    final anchor = html.AnchorElement(href: url)
      ..setAttribute('download', 'navi_career_report.pdf')
      ..click();
    html.Url.revokeObjectUrl(url);
  }

  String _buildEmailBody() {
    final m = widget.match;
    final r = widget.roadmap;
    final lines = [
      'My Navi Career Report',
      '',
      'Top Career Match: ${m.title}',
      'Confidence: ${m.confidence}%',
      'Salary Range: ${m.salaryRange}',
      '',
      if (m.reasons.isNotEmpty) ...[
        'Why this career fits:',
        ...m.reasons.map((s) => '  - $s'),
        '',
      ],
      if (r.years.isNotEmpty) ...[
        'Roadmap:',
        for (final year in r.years) ...[
          '  ${year.label}:',
          ...year.milestones.map((ms) => '    - $ms'),
        ],
        '',
      ],
      'Generated by Navi - AI Career Guidance for Filipino IT Students',
    ];
    return lines.join('\n');
  }

  Future<void> _emailPdf() async {
    final subject = Uri.encodeComponent(
      'My Navi Career Report - ${widget.match.title}',
    );
    final body = Uri.encodeComponent(_buildEmailBody());
    final uri = Uri.parse('mailto:?subject=$subject&body=$body');
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 28),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 40,
            height: 4,
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: NaviColors.primaryPale,
              borderRadius: BorderRadius.circular(100),
            ),
          ),
          Row(
            children: [
              Container(
                height: 42,
                width: 42,
                decoration: BoxDecoration(
                  color: NaviColors.sparkGreen.withValues(alpha: 0.14),
                  shape: BoxShape.circle,
                ),
                child: const Icon(
                  Icons.picture_as_pdf_rounded,
                  color: NaviColors.sparkGreen,
                  size: 22,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Export as PDF',
                      style: NaviTextStyles.bodyLarge.copyWith(
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Download or email your career report',
                      style: NaviTextStyles.label.copyWith(fontSize: 12),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 18),
          if (_generating) ...[
            const SizedBox(height: 12),
            const CircularProgressIndicator(
              color: NaviColors.primary,
              strokeWidth: 2.5,
            ),
            const SizedBox(height: 14),
            Text(
              'Generating your report...',
              style: NaviTextStyles.bodyMedium.copyWith(
                color: NaviColors.textMid,
              ),
            ),
            const SizedBox(height: 8),
          ],
          if (_error != null) ...[
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: NaviColors.sparkPink.withValues(alpha: 0.16),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Text(
                _error!,
                style: NaviTextStyles.bodyMedium.copyWith(
                  color: NaviColors.textDark,
                  fontSize: 12,
                ),
              ),
            ),
            const SizedBox(height: 14),
          ],
          if (_done) ...[
            _buildPdfPreview(),
            const SizedBox(height: 16),
          ],
          if (!_generating)
            Row(
              children: [
                Expanded(
                  child: _ActionCard(
                    icon: Icons.download_rounded,
                    iconColor: NaviColors.primary,
                    label: 'Download PDF',
                    subtitle: 'Save to your device',
                    onTap: _done ? _downloadPdf : null,
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: _ActionCard(
                    icon: Icons.email_rounded,
                    iconColor: NaviColors.sparkGreen,
                    label: 'Email',
                    subtitle: 'Send report summary',
                    onTap: _done ? _emailPdf : null,
                  ),
                ),
              ],
            ),
        ],
      ),
    );
  }

  Widget _buildPdfPreview() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: NaviColors.sparkGreen.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: NaviColors.sparkGreen.withValues(alpha: 0.2),
        ),
      ),
      child: Row(
        children: [
          Container(
            height: 38,
            width: 32,
            decoration: BoxDecoration(
              color: NaviColors.sparkGreen.withValues(alpha: 0.16),
              borderRadius: BorderRadius.circular(6),
            ),
            child: const Icon(
              Icons.description_rounded,
              color: NaviColors.sparkGreen,
              size: 18,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'navi_career_report.pdf',
                  style: NaviTextStyles.bodyMedium.copyWith(
                    color: NaviColors.textDark,
                    fontWeight: FontWeight.w800,
                    fontSize: 12,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  'Includes: Career Match, Radar Chart, Strengths, '
                  'Weaknesses, Roadmap, Skills, Salary',
                  style: NaviTextStyles.label.copyWith(fontSize: 10),
                ),
              ],
            ),
          ),
          const Icon(
            Icons.check_circle_rounded,
            color: NaviColors.sparkGreen,
            size: 20,
          ),
        ],
      ),
    );
  }
}

class _ActionCard extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String label;
  final String subtitle;
  final VoidCallback? onTap;

  const _ActionCard({
    required this.icon,
    required this.iconColor,
    required this.label,
    required this.subtitle,
    this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final enabled = onTap != null;
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(16),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 18, horizontal: 12),
          decoration: BoxDecoration(
            color: enabled
                ? iconColor.withValues(alpha: 0.06)
                : NaviColors.textMuted.withValues(alpha: 0.06),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: enabled
                  ? iconColor.withValues(alpha: 0.2)
                  : NaviColors.textMuted.withValues(alpha: 0.15),
            ),
          ),
          child: Column(
            children: [
              Icon(
                icon,
                size: 28,
                color: enabled
                    ? iconColor
                    : NaviColors.textMuted,
              ),
              const SizedBox(height: 8),
              Text(
                label,
                style: NaviTextStyles.bodyMedium.copyWith(
                  fontWeight: FontWeight.w800,
                  fontSize: 13,
                  color: enabled ? NaviColors.textDark : NaviColors.textMuted,
                ),
              ),
              const SizedBox(height: 2),
              Text(
                subtitle,
                style: NaviTextStyles.label.copyWith(
                  fontSize: 10,
                  color: enabled ? NaviColors.textMid : NaviColors.textMuted,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
