import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../quiz/quiz_session.dart';
import '../results/recommendation_result.dart';
import '../roadmap/roadmap_plan.dart';
import 'pdf_generator.dart';

class PdfExportSheet extends StatefulWidget {
  final CareerRecommendation match;
  final RoadmapPlan roadmap;
  final QuizSession session;

  const PdfExportSheet({
    super.key,
    required this.match,
    required this.roadmap,
    required this.session,
  });

  @override
  State<PdfExportSheet> createState() => _PdfExportSheetState();
}

class _PdfExportSheetState extends State<PdfExportSheet> {
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController();

  bool _generating = true;
  bool _done = false;
  bool _sending = false;
  String? _error;
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    _generatePdf();
  }

  @override
  void dispose() {
    _emailController.dispose();
    super.dispose();
  }

  Future<void> _generatePdf() async {
    try {
      setState(() => _error = null);

      final doc = await PdfExportGenerator.generate(
        match: widget.match,
        roadmap: widget.roadmap,
        session: widget.session,
      );

      final bytes = await doc.save();
      final pdfBytes = Uint8List.fromList(bytes);

      if (!mounted) return;
      setState(() {
        _pdfBytes = pdfBytes;
        _generating = false;
        _done = true;
      });
    } catch (e) {
      if (!mounted) return;
      final errorMsg = e.toString();
      final shortMsg = errorMsg.length > 120
          ? '${errorMsg.substring(0, 120)}...'
          : errorMsg;
      setState(() {
        _generating = false;
        _error =
            'Failed to generate PDF.\n\nError: $shortMsg\n\nPlease try again or check your data.';
      });
    }
  }

  String _buildEmailBody() {
    final m = widget.match;
    final r = widget.roadmap;
    final lines = [
      'My Navi Career Report',
      '',
      'Top Career Match: ${m.title}',
      'Confidence: ${m.confidence}%',
      'Salary Range: ${m.salaryRange}',
      '',
      if (m.reasons.isNotEmpty) ...[
        'Why this career fits:',
        ...m.reasons.map((s) => '  - $s'),
        '',
      ],
      if (r.years.isNotEmpty) ...[
        'Roadmap:',
        for (final year in r.years) ...[
          '  ${year.label}:',
          ...year.milestones.map((ms) => '    - $ms'),
        ],
        '',
      ],
      'Generated by Navi - AI Career Guidance for Filipino IT Students',
    ];
    return lines.join('\n');
  }

  Future<void> _emailPdf() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _sending = true);

    final email = _emailController.text.trim();
    final subject = Uri.encodeComponent(
      'My Navi Career Report - ${widget.match.title}',
    );
    final body = Uri.encodeComponent(_buildEmailBody());
    final uri = Uri.parse('mailto:$email?subject=$subject&body=$body');
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    }

    if (mounted) setState(() => _sending = false);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 28),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 40,
            height: 4,
            margin: const EdgeInsets.only(bottom: 16),
            decoration: BoxDecoration(
              color: NaviColors.primaryPale,
              borderRadius: BorderRadius.circular(100),
            ),
          ),
          Row(
            children: [
              Container(
                height: 42,
                width: 42,
                decoration: BoxDecoration(
                  color: NaviColors.sparkGreen.withValues(alpha: 0.14),
                  shape: BoxShape.circle,
                ),
                child: const Icon(
                  Icons.picture_as_pdf_rounded,
                  color: NaviColors.sparkGreen,
                  size: 22,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Export as PDF',
                      style: NaviTextStyles.bodyLarge.copyWith(
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Enter your email to receive the report',
                      style: NaviTextStyles.label.copyWith(fontSize: 12),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 18),
          if (_generating) ...[
            const SizedBox(height: 12),
            const CircularProgressIndicator(
              color: NaviColors.primary,
              strokeWidth: 2.5,
            ),
            const SizedBox(height: 14),
            Text(
              'Generating your report...',
              style: NaviTextStyles.bodyMedium.copyWith(
                color: NaviColors.textMid,
              ),
            ),
            const SizedBox(height: 8),
          ],
          if (_error != null) ...[
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: NaviColors.sparkPink.withValues(alpha: 0.16),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Text(
                _error!,
                style: NaviTextStyles.bodyMedium.copyWith(
                  color: NaviColors.textDark,
                  fontSize: 12,
                ),
              ),
            ),
            const SizedBox(height: 14),
          ],
          if (_done) ...[
            _buildPdfPreview(),
            const SizedBox(height: 16),
            Form(
              key: _formKey,
              child: TextFormField(
                controller: _emailController,
                keyboardType: TextInputType.emailAddress,
                textInputAction: TextInputAction.done,
                decoration: InputDecoration(
                  hintText: 'your@email.com',
                  labelText: 'Your email address',
                  prefixIcon: const Icon(
                    Icons.email_outlined,
                    size: 20,
                  ),
                  filled: true,
                  fillColor: NaviColors.primaryPale.withValues(alpha: 0.08),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: BorderSide(
                      color: NaviColors.textMuted.withValues(alpha: 0.2),
                    ),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: BorderSide(
                      color: NaviColors.textMuted.withValues(alpha: 0.2),
                    ),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(
                      color: NaviColors.primary,
                      width: 1.5,
                    ),
                  ),
                  errorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(
                      color: NaviColors.sparkPink,
                    ),
                  ),
                  focusedErrorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(
                      color: NaviColors.sparkPink,
                      width: 1.5,
                    ),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 14,
                  ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter your email';
                  }
                  final emailRegex = RegExp(
                    r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
                  );
                  if (!emailRegex.hasMatch(value.trim())) {
                    return 'Please enter a valid email';
                  }
                  return null;
                },
                onFieldSubmitted: (_) => _emailPdf(),
              ),
            ),
            const SizedBox(height: 14),
          ],
          if (!_generating)
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                onPressed: _done && !_sending ? _emailPdf : null,
                icon: _sending
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      )
                    : const Icon(Icons.send_rounded, size: 18),
                label: Text(_sending ? 'Opening email...' : 'Send Report'),
                style: FilledButton.styleFrom(
                  backgroundColor: NaviColors.primary,
                  foregroundColor: Colors.white,
                  disabledBackgroundColor:
                      NaviColors.textMuted.withValues(alpha: 0.3),
                  disabledForegroundColor:
                      NaviColors.textMuted.withValues(alpha: 0.6),
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildPdfPreview() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: NaviColors.sparkGreen.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: NaviColors.sparkGreen.withValues(alpha: 0.2),
        ),
      ),
      child: Row(
        children: [
          Container(
            height: 38,
            width: 32,
            decoration: BoxDecoration(
              color: NaviColors.sparkGreen.withValues(alpha: 0.16),
              borderRadius: BorderRadius.circular(6),
            ),
            child: const Icon(
              Icons.description_rounded,
              color: NaviColors.sparkGreen,
              size: 18,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'navi_career_report.pdf',
                  style: NaviTextStyles.bodyMedium.copyWith(
                    color: NaviColors.textDark,
                    fontWeight: FontWeight.w800,
                    fontSize: 12,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  'Career Match, Roadmap, Skills, Salary',
                  style: NaviTextStyles.label.copyWith(fontSize: 10),
                ),
              ],
            ),
          ),
          const Icon(
            Icons.check_circle_rounded,
            color: NaviColors.sparkGreen,
            size: 20,
          ),
        ],
      ),
    );
  }
}
